### ISSUE TITLE
Failed to convert text layer

### ISSUE THREAD

**Issue by zlel** [nicklasaven/TileLess#11]
Now, I can use "tileless.pack_twkb_polygon" to convert polygon layer, and also use "tileless.pack_twkb_linestring" to convert line layer, but I don't know how to convert point layer up to this time. For example I have a text layer with the geometry type of point, How can I use this tool to finish the conversion?

**Comment by nicklasaven** [comment]
About points the styling  isn't ready. It can render 1 pixel points, but that is not very usable. There wilö be symbols for points, but not yet
 About text I haven't made a function for putting things together yet. I can write you som instructions next week. Don't have any computer now.

**Comment by zlel** [comment]
Thank you very much. 
I am waiting for your reply to the steps on the text conversion. If you have time, please give me some instructions.

**Comment by nicklasaven** [comment]
Ok, what you have to do is write your data to the database with the function tileless.twkb_write2sqlite

But we split the process in 3 steps to make things a little clearer.

When styling text there are at least 3 parameters: size, color and font. In tileless_map the fonts are loaded to the gpu at startup. That is much faster than loading them for each text draw. But that also means that we cannot use very many different fonts and sizes, since the create the full character set for each font and size. So, for now it only creates 3 sizes (hardcoded in function init_text_resources(), but taht have to be done in a better way in the future). All 3 sizes now uses the same font. To give the right size to the right text you have to put an integer value from 1 to 3 (1 is smaller and 3 is larger) in a field in the text table. To handle the color you put a style field in the text table with values that you use in the style table in the sqlite db.

Another thing that has to be improved is htat all text now starts at the point you give. It cannot rinder to the left or use the point as anchor in the middle. That is also for the future. Text cannot either be rotated yet.

So, let's make an example. Let's say we have a table with text. It has points where the text should be started , and it has a color field with values like "red", "black" and "green". It also have sizes in points like 12, 14, 22, 26 and 32.

So first we create a view to make data sute tileless_map. If we have to transform data to an UTM-zone we do that in this step too.

original table:
```
orig_table(
gid serial primary key,
geom geometry(point, 4326),
color text,
size int,
text text)
```

From that table we create a view. I use to not do anything about the size yet, to keep the original value and make it possible to tweak the sizes in tileless_map.
```
CREATE VIEW tileless_text AS
SELECT gid, ST_Transform(geom, 32633) geom, CASE WHEN color = 'black' THEN 1 WHEN color = 'red' then 2 WHEN color = 'green' THEN 3 color_int, size, text FROM orig_table;
```
Ok, now we have a view. step 2 is writing to sqlite db:

The function tileless.twkb_write2sqlite has a lot of parameters. 
```
(
    sqlitedb text, – This is the name of the db to write to
    dataset_name text, – name of the resulting table in the db
    sql_string text, --A sql to get the data we want to add (don’t use this sql to do what we did in the view. That will mess up the spatial index creation if you transform or change name of fields for id or geometry, but you have to create twkb in this sql)
    twkb_name text, --name of the twkb-data in the sql above
    id_name text, – name of a unique id in the sql above
    idx_tbl text, – Name of the table to create the spatial index from
    idx_geom text DEFAULT ''::text, – name of the geometry field to create the spatial index from
    idx_id text DEFAULT ''::text, – name of id-field to be used in the index that corresponds to the id in the text-table
    create_table integer DEFAULT 1 –If the table should be created in the spatialite db or data should just be appended to tan existing table
)
```

So in our example it could look something like:
```
SELECT  tileless.twkb_write2sqlite(‘the_db’, ‘text_table’, ‘SELECT gid twkb_id, ST_ASTWKB(geom) twkb, color_int, size, text FROM tileless_text;’, ‘twkb’, ‘twkb_id’, ‘tileless_text’, ‘geom’, ‘gid’, 1);
```
Ok, now we have the data in the db. But we still haven’t normalized the sizes. I use to do that in the sqlite db like this:


```
alter table text_table add column size_enum int;

/*column size below isn’t used for now, but that will be the size used when creating the font in tileless_map. But that is not implemented yet.*/

create table norm_size(max float, min float, size int, val int);

insert into norm_size (max, min, val, out) values
(0,10,8, 1),
(10,15,14,2),
(15,35,25,3);

update text_table set size_enum = (select val from norm_size n where text_table.size > n.min and text_table.size <= n.max);
```
Maybe it would be better to do this at runtime, but I have tried to avoid joining at runtime when possible to keep it fast. But with indexes it would probably be acceptable

Now you have to do the same things as with the other tables:
add entry in geometry_columns
add entries in style table
add entry in layers table
And, you will also have to add entry in text_conf telling what fields is used for size and text. The fields anchor_fld and  rotation_fld isn’t used yet, and the field program isn’t used any more. LayerID should correspond to layerID in the layers table. 

That’s it :-)
